#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

# Hash one or more font header files into a signed 32-bit int.
hash_files() {
  ruby -rdigest -e \
    'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' \
    "$@"
}

# Emit a reading-font ID define.
# When the noemoji/ directory exists, emits an #ifdef OMIT_EMOJI_FONTS block so
# the correct hash is selected at compile time.
# Usage: reading_font_id DEFINE_NAME file1 [file2 ...]
#   Files are relative paths from builtinFonts/ (e.g. ./lexenddeca_10_regular.h).
#   Noemoji counterparts are assumed to live at noemoji/<basename>.
reading_font_id() {
  local name="$1"; shift
  local files=("$@")

  if [ -d "./noemoji" ]; then
    local noemoji_files=()
    for f in "${files[@]}"; do
      noemoji_files+=("./noemoji/$(basename "$f")")
    done
    echo "#ifdef OMIT_EMOJI_FONTS"
    echo "#define ${name} ($(hash_files "${noemoji_files[@]}"))"
    echo "#else"
    echo "#define ${name} ($(hash_files "${files[@]}"))"
    echo "#endif"
  else
    echo "#define ${name} ($(hash_files "${files[@]}"))"
  fi
}

# NotoEmoji / NotoSymbols — standalone emoji font IDs (no noemoji variant needed)
echo "#define NOTOEMOJI_10_FONT_ID ($(hash_files ./notoemoji_10_regular.h))"
echo "#define NOTOEMOJI_12_FONT_ID ($(hash_files ./notoemoji_12_regular.h))"
echo "#define NOTOEMOJI_14_FONT_ID ($(hash_files ./notoemoji_14_regular.h))"
echo "#define NOTOEMOJI_16_FONT_ID ($(hash_files ./notoemoji_16_regular.h))"
echo "#define NOTOSYMBOLS_10_FONT_ID ($(hash_files ./notosymbols_10_regular.h))"
echo "#define NOTOSYMBOLS_12_FONT_ID ($(hash_files ./notosymbols_12_regular.h))"
echo "#define NOTOSYMBOLS_14_FONT_ID ($(hash_files ./notosymbols_14_regular.h))"
echo "#define NOTOSYMBOLS_16_FONT_ID ($(hash_files ./notosymbols_16_regular.h))"

# Reading fonts - support OMIT_EMOJI_FONTS
reading_font_id LEXENDDECA_8_FONT_ID \
  ./lexenddeca_8_regular.h ./lexenddeca_8_bold.h ./lexenddeca_8_bolditalic.h ./lexenddeca_8_italic.h
reading_font_id LEXENDDECA_10_FONT_ID \
  ./lexenddeca_10_regular.h ./lexenddeca_10_bold.h ./lexenddeca_10_bolditalic.h ./lexenddeca_10_italic.h
reading_font_id LEXENDDECA_12_FONT_ID \
  ./lexenddeca_12_regular.h ./lexenddeca_12_bold.h ./lexenddeca_12_bolditalic.h ./lexenddeca_12_italic.h
reading_font_id LEXENDDECA_14_FONT_ID \
  ./lexenddeca_14_regular.h ./lexenddeca_14_bold.h ./lexenddeca_14_bolditalic.h ./lexenddeca_14_italic.h
reading_font_id LEXENDDECA_16_FONT_ID \
  ./lexenddeca_16_regular.h ./lexenddeca_16_bold.h ./lexenddeca_16_bolditalic.h ./lexenddeca_16_italic.h
reading_font_id LEXENDDECA_18_FONT_ID \
  ./lexenddeca_18_regular.h ./lexenddeca_18_bold.h ./lexenddeca_18_bolditalic.h ./lexenddeca_18_italic.h
reading_font_id LEXENDDECA_20_FONT_ID \
  ./lexenddeca_20_regular.h ./lexenddeca_20_bold.h ./lexenddeca_20_bolditalic.h ./lexenddeca_20_italic.h

reading_font_id CHAREINK_8_FONT_ID \
  ./charein_8_regular.h ./charein_8_bold.h ./charein_8_bolditalic.h ./charein_8_italic.h
reading_font_id CHAREINK_10_FONT_ID \
  ./charein_10_regular.h ./charein_10_bold.h ./charein_10_bolditalic.h ./charein_10_italic.h
reading_font_id CHAREINK_12_FONT_ID \
  ./charein_12_regular.h ./charein_12_bold.h ./charein_12_bolditalic.h ./charein_12_italic.h
reading_font_id CHAREINK_14_FONT_ID \
  ./charein_14_regular.h ./charein_14_bold.h ./charein_14_bolditalic.h ./charein_14_italic.h
reading_font_id CHAREINK_16_FONT_ID \
  ./charein_16_regular.h ./charein_16_bold.h ./charein_16_bolditalic.h ./charein_16_italic.h
reading_font_id CHAREINK_18_FONT_ID \
  ./charein_18_regular.h ./charein_18_bold.h ./charein_18_bolditalic.h ./charein_18_italic.h
reading_font_id CHAREINK_20_FONT_ID \
  ./charein_20_regular.h ./charein_20_bold.h ./charein_20_bolditalic.h ./charein_20_italic.h

reading_font_id BITTER_8_FONT_ID \
  ./bitter_8_regular.h ./bitter_8_bold.h ./bitter_8_bolditalic.h ./bitter_8_italic.h
reading_font_id BITTER_10_FONT_ID \
  ./bitter_10_regular.h ./bitter_10_bold.h ./bitter_10_bolditalic.h ./bitter_10_italic.h
reading_font_id BITTER_12_FONT_ID \
  ./bitter_12_regular.h ./bitter_12_bold.h ./bitter_12_bolditalic.h ./bitter_12_italic.h
reading_font_id BITTER_14_FONT_ID \
  ./bitter_14_regular.h ./bitter_14_bold.h ./bitter_14_bolditalic.h ./bitter_14_italic.h
reading_font_id BITTER_16_FONT_ID \
  ./bitter_16_regular.h ./bitter_16_bold.h ./bitter_16_bolditalic.h ./bitter_16_italic.h
reading_font_id BITTER_18_FONT_ID \
  ./bitter_18_regular.h ./bitter_18_bold.h ./bitter_18_bolditalic.h ./bitter_18_italic.h
reading_font_id BITTER_20_FONT_ID \
  ./bitter_20_regular.h ./bitter_20_bold.h ./bitter_20_bolditalic.h ./bitter_20_italic.h

# UI fonts — no emoji variant
echo "#define UI_10_FONT_ID ($(hash_files ./ubuntu_10_regular.h ./ubuntu_10_bold.h))"
echo "#define UI_12_FONT_ID ($(hash_files ./ubuntu_12_regular.h ./ubuntu_12_bold.h))"
echo "#define SMALL_FONT_ID ($(hash_files ./inter_8_regular.h))"

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."
for id in \
  NOTOEMOJI_10_FONT_ID NOTOEMOJI_12_FONT_ID NOTOEMOJI_14_FONT_ID NOTOEMOJI_16_FONT_ID \
  NOTOSYMBOLS_10_FONT_ID NOTOSYMBOLS_12_FONT_ID NOTOSYMBOLS_14_FONT_ID NOTOSYMBOLS_16_FONT_ID \
  LEXENDDECA_8_FONT_ID LEXENDDECA_10_FONT_ID LEXENDDECA_12_FONT_ID LEXENDDECA_14_FONT_ID \
  LEXENDDECA_16_FONT_ID LEXENDDECA_18_FONT_ID LEXENDDECA_20_FONT_ID \
  CHAREINK_8_FONT_ID CHAREINK_10_FONT_ID CHAREINK_12_FONT_ID CHAREINK_14_FONT_ID \
  CHAREINK_16_FONT_ID CHAREINK_18_FONT_ID CHAREINK_20_FONT_ID \
  BITTER_8_FONT_ID BITTER_10_FONT_ID BITTER_12_FONT_ID BITTER_14_FONT_ID \
  BITTER_16_FONT_ID BITTER_18_FONT_ID BITTER_20_FONT_ID \
  UI_10_FONT_ID UI_12_FONT_ID SMALL_FONT_ID; do
  echo "static_assert(${id} != 0, \"Font ID collision with sentinel\");"
done
